version: '3.8'

services:
  djangorest:
    build: .
    # Временная команда для вывода переменных окружения
    command: sh -c "env && uvicorn proxy_server.asgi:application --host 0.0.0.0 --port 8002 --reload"
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    hostname: djangorest
    container_name: djangorest
    networks:
      - shared_network

networks:
  shared_network:
    external: true